# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7bda87a6a734716008ad0cdb77a544a69b9961b6b28295f0b7003630e2194653735c0ec371c8dab14143c36c788abe463cf5eaaafa5c9e8611e73687e9a49e0

test:
  secret_key_base: 92f07adf31d08e0f96543757ec6ddebce2ab0158d5b19fbaecd064f0e0467b8490ed7d05ab986fb189d2e00ba0bfd3c736324dabca1eab13cd1be48e2f698de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= Settings[:secret] %>
